### ISSUE TITLE
You spelled "integer" as "interger" in that first jpg.

### ISSUE THREAD

**Issue by jwasher** [AbdulMalikDev/PythonCheatSheet#2]
I was going to do a PR, but, I can't for a jpg.. you here's an issue instead.

**Comment by AbdulMalikDev** [comment]
Since that is a picture taken from geeksforgeeks.com, photoshop or similar software has to be used to rectify this mistake. Until a PR with correct image is not submited, i'm afraid this might exists as it is.

**Comment by AbdulMalikDev** [comment]
Fixed by @Abrar-04 #5
